### ISSUE TITLE
Suggestions for use

### ISSUE THREAD

**Issue by kuafuRace** [develop-suda/typ_engineer_API#9]
https://github.com/develop-suda/typ_engineer_API/blob/5db6938da1e32afa1ffce2c2e6296ba1f3858923/internal/log/log.go#L17
You can use like this
year, month, day := carbon.Now().Date()

**Comment by develop-suda** [comment]
I did not know this way of writing, I learned a lot!
I will fix it to gouguoyin way of writing. Thanks for the confirmation!
